Refactored to components
heisch/gloomhaven-item-db pull request #8
Opened 2020-07-10 02:00 UTC by solomojb

Hello Again,

  This is a pretty big change. I apologize, i might have gone a little overboard with it, but i think you'll see it'll make adding things a lot simpler going forward.

  At your convenience please review and test. 

Jim

2020-07-16 09:16 UTC, heisch commented
I didn't forget this I'm just super busy at the moment. Will have a look at this soon™.

2020-07-16 12:08 UTC, solomojb commented
No worries. I promise future changes will be smaller feature sized improvements.

Working on “party mode” now. Almost have it working.

Also created the ability to filter multiple slots and added for the most part the fallen circle cards. (I didn’t fully track down their sources hoping the community will help)

Sent from my iPhone

On Jul 16, 2020, at 5:17 AM, Nicola Heisch <notifications@github.com> wrote:

﻿

I didn't forget this I'm just super busy at the moment. Will have a look at this soon™.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fheisch%2Fgloomhaven-item-db%2Fpull%2F8%23issuecomment-659283691&data=02%7C01%7C%7C0753127ed432409934e408d82969066e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637304878330577624&sdata=ZOSA3k3nDKf%2Fp3ZAkbuLLH5oR7kO%2BCXZhAhsb4AmScM%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGTSK2W6JHLLBZJGDZ2PPMDR33ARRANCNFSM4OWEVUNQ&data=02%7C01%7C%7C0753127ed432409934e408d82969066e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637304878330577624&sdata=9Zw9MP%2FODAPN6rv3MwbVh4k%2F13XsB9L5l0l7HUm3Sfw%3D&reserved=0>.

2020-07-28 11:08 UTC, heisch requested changes
Other than some minor nitpicks this looks very good.
Please address the issues and then you can tell me when this is ready to publish

2020-07-28 11:08 UTC, heisch commented on .gitmodules
> +	url = https://github.com/any2cards/gloomhaven.git
any particular reason for this change?

2020-07-28 11:08 UTC, heisch commented on src/components/Tabs/SpoilerFilters/SpoilerFilterItemList.tsx
> +        checkBoxes.push(<FilterCheckbox id={i}/>);
Each child in a list should have a unique "key" prop.

2020-07-28 11:08 UTC, heisch commented on src/components/Tabs/MainView/ItemCard.tsx
> +export default ItemCard;
Can you set up your editor/IDE to always add a newline at the end of a file when saving?

2020-07-28 11:08 UTC, heisch commented on src/components/Tabs/MainView/ItemGrid.tsx
> +        <>
Didn't know there is a short syntax for <React.Fragment> cool

2020-07-28 11:08 UTC, heisch commented on src/components/Tabs/MainView/ItemList.tsx
> +            console.log(newProperty, newDirection);
forgotten debug statement

2020-07-28 11:08 UTC, heisch commented on src/components/Tabs/MainView/ItemManagement.tsx
> +                </>
Please always use brackets for multi-line html
```js
return (
  <>
    {item.count};
  </>
);
```

2020-07-29 02:58 UTC, solomojb commented on .gitmodules
> +	url = https://github.com/any2cards/gloomhaven.git
I updated to the head of the submodule to get access to the Fallen Circle Cards. (Which will be in a future branch)

2020-07-29 03:00 UTC, solomojb commented on src/components/Tabs/SpoilerFilters/SpoilerFilterItemList.tsx
> +        checkBoxes.push(<FilterCheckbox id={i}/>);
Added

2020-07-29 03:03 UTC, solomojb commented on src/components/Tabs/MainView/ItemCard.tsx
> +export default ItemCard;
Done!

2020-07-29 03:03 UTC, solomojb commented on src/components/Tabs/MainView/ItemList.tsx
> +            console.log(newProperty, newDirection);
oops good catch

2020-07-29 03:14 UTC, solomojb commented
I pushed the fixes to the code.

2020-07-29 09:41 UTC, heisch approved these changes

2020-07-29 09:42 UTC, merged